project:
  type: book
  output-dir: docs

book:
  title: "MA500: Introduction to R"
  chapters:
    - index.qmd
    - 01_install.qmd


bibliography: references.bib

format:
  html:
    theme:
      - minty
    css: styles.css
    highlight-style: tango
    code-fold: show
    code-summary: "hide code"
  pdf:
    documentclass: scrreprt

editor: visual

