project:
  type: book
  output-dir: docs

book:
  title: "MA500: Introduction to R"
  chapters:
    - index.qmd
    - 01_install.qmd
    - 03_Basics.qmd
    - 04_CLF.qmd
    - 05_Dataframes.qmd
    - 06_Visualizations.qmd
    - 07_EDA.qmd
    
execute: 
  error: true

bibliography: references.bib

format:
  html:
    theme:
      - minty
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    css: styles.css
    highlight-style: tango
    code-fold: show
    code-summary: "hide code"
  pdf:
    documentclass: scrreprt

editor: visual

