<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Dataframes – MA500: Introduction to R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06_Visualizations.html" rel="next">
<link href="./04_CLF.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-0de45b8b5f35a93596f1d788d60c4c11.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-94859c87fd2e0f79297c4bdcf1025212.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05_Dataframes.html">Introduction to Dataframes</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MA500: Introduction to R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MA-500: Introduction to R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_install.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R/RStudio Installation Guide</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Basics &amp; Fundamentals</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_CLF.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conditionals, Loops, and Functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_Dataframes.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Introduction to Dataframes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_Visualizations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Visualizations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_EDA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory Data Analysis</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-is-a-data.frame" id="toc-what-is-a-data.frame" class="nav-link active" data-scroll-target="#what-is-a-data.frame">What is a <code>data.frame</code>?</a></li>
  <li><a href="#what-is-tidyverse" id="toc-what-is-tidyverse" class="nav-link" data-scroll-target="#what-is-tidyverse">What is <code>tidyverse</code>?</a></li>
  <li><a href="#what-is-ggplot2" id="toc-what-is-ggplot2" class="nav-link" data-scroll-target="#what-is-ggplot2">What is <code>ggplot2</code>?</a></li>
  <li><a href="#creating-a-data.frame" id="toc-creating-a-data.frame" class="nav-link" data-scroll-target="#creating-a-data.frame">Creating a Data.frame</a>
  <ul class="collapse">
  <li><a href="#defining-in-r" id="toc-defining-in-r" class="nav-link" data-scroll-target="#defining-in-r">Defining in R</a></li>
  <li><a href="#reading-in-a-.csv" id="toc-reading-in-a-.csv" class="nav-link" data-scroll-target="#reading-in-a-.csv">Reading in a <code>.csv</code></a></li>
  </ul></li>
  <li><a href="#analyzing-the-data" id="toc-analyzing-the-data" class="nav-link" data-scroll-target="#analyzing-the-data">Analyzing the data</a></li>
  <li><a href="#visualizing-the-data" id="toc-visualizing-the-data" class="nav-link" data-scroll-target="#visualizing-the-data">Visualizing the data</a></li>
  <li><a href="#data-transformation" id="toc-data-transformation" class="nav-link" data-scroll-target="#data-transformation">Data Transformation</a>
  <ul class="collapse">
  <li><a href="#dplyr" id="toc-dplyr" class="nav-link" data-scroll-target="#dplyr">Dplyr</a></li>
  </ul></li>
  <li><a href="#merging" id="toc-merging" class="nav-link" data-scroll-target="#merging">Merging</a>
  <ul class="collapse">
  <li><a href="#join-functions" id="toc-join-functions" class="nav-link" data-scroll-target="#join-functions">Join Functions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to Dataframes</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="what-is-a-data.frame" class="level3">
<h3 class="anchored" data-anchor-id="what-is-a-data.frame">What is a <code>data.frame</code>?</h3>
<p>A <code>data.frame</code> in <code>R</code> is a data structure used to store data in a tabular form. It is very similar to a spreadsheet, excel sheet, or SQL table within R. You can also think of it as a collection of multiple data vectors. A <code>data.frame</code> is two-dimensional, meaning it has rows and columns where:</p>
<ul>
<li>each <em>row</em> represents an observation</li>
<li>each <em>column</em> represents a variable, attribute, or feature.</li>
</ul>
</section>
<section id="what-is-tidyverse" class="level3">
<h3 class="anchored" data-anchor-id="what-is-tidyverse">What is <code>tidyverse</code>?</h3>
<p><code>Tidyverse</code> is a collection of packages to help with cleaning, transformation, visualization, and analysis. (A few packages in <code>Tidyverse</code> include <code>dplyr</code>, <code>ggplot2</code>, <code>tidyr</code>, and <code>readr</code>). In this class, we will be using this collection for data wrangling, cleaning, and transforming.</p>
<p>You can install tidyverse by running: <code>install.packages("tidyverse")</code>.</p>
</section>
<section id="what-is-ggplot2" class="level3">
<h3 class="anchored" data-anchor-id="what-is-ggplot2">What is <code>ggplot2</code>?</h3>
<p>This is <em>the</em> R package for data visualization. This suite provides an easy way to visualize your data with: bar charts, scatter plots, time trends, etc. Writing ggplot code comprises of these components: the data being visualized, the aesthetics (how you would like the variables to be mapped), and geometric objects (the shapes that represent the data).</p>
<p>Note: Installing <code>tidyverse</code> also installs <code>ggplot2</code>, since it’s one of the core packages included.</p>
</section>
<section id="creating-a-data.frame" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-data.frame">Creating a Data.frame</h2>
<p>You can build a <code>data.frame</code> either by defining it within R or by reading data from a <code>.csv</code> or <code>.xlsx</code> file.</p>
<section id="defining-in-r" class="level3">
<h3 class="anchored" data-anchor-id="defining-in-r">Defining in R</h3>
<div class="callout-example">
<p>Let’s add our previously defined vectors in a <code>data.frame</code>. <img src="images/clipboard-3553642164.png" class="img-fluid" width="1200"></p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>tr_21 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">352818</span>, <span class="dv">296806</span>, <span class="dv">65110</span>, <span class="dv">35612</span>, <span class="dv">12372</span>, <span class="dv">10100</span>, <span class="dv">34978</span>, <span class="dv">3519</span>, <span class="dv">3761</span>, <span class="dv">1395</span>, <span class="dv">0</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>tr_22 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">372492</span>, <span class="dv">327115</span>, <span class="dv">76141</span>, <span class="dv">35794</span>, <span class="dv">18169</span>, <span class="dv">9353</span>, <span class="dv">31643</span>, <span class="dv">4953</span>, <span class="dv">3562</span>, <span class="dv">1473</span>, <span class="dv">0</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>categories <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Income"</span>, <span class="st">"Gross Receipts"</span>, <span class="st">"Section 30 Federal income tax"</span>, <span class="st">"Property"</span>, <span class="st">"Hotel Occupancy"</span>, <span class="st">"Liquid Fuel"</span>, <span class="st">"Tabacco"</span>, <span class="st">"Alcoholic Beverages"</span>, <span class="st">"Excise"</span>, <span class="st">"Lmited Gaming"</span>, <span class="st">"Other"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>tax_rev <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">description =</span> categories, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">tax_2021 =</span> tr_21, </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">tax_2022 =</span> tr_22)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(tax_rev))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                    description tax_2021 tax_2022
1                        Income   352818   372492
2                Gross Receipts   296806   327115
3 Section 30 Federal income tax    65110    76141
4                      Property    35612    35794
5               Hotel Occupancy    12372    18169
6                   Liquid Fuel    10100     9353</code></pre>
</div>
</div>
</div>
</section>
<section id="reading-in-a-.csv" class="level3">
<h3 class="anchored" data-anchor-id="reading-in-a-.csv">Reading in a <code>.csv</code></h3>
<p>To read a separate <code>.csv</code> file into R, we will use the <code>read_csv</code> function from the <code>readr</code> package (also part of <code>tidyverse</code>).</p>
<div class="callout-example">
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># personal preference for me is to create a separate string that is my parent folder</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dir <span class="ot">&lt;-</span> <span class="st">"/Users/rdominguez/Documents/MA500/Lessons/datasets/"</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>ow <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">paste0</span>(dir, <span class="st">"overwatch_stats.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 87 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): Player, Date, Map, Mode, Role
dbl (7): Win, Elimination, Assists, Deaths, Damage, Heals, Mitigation

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</div>
</section>
</section>
<section id="analyzing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-the-data">Analyzing the data</h2>
<p>Once your data is loaded into R, the best first steps is to inspect it. The main focus: get familiar with the data and summarize its main characteristics.</p>
<p>The <code>head()</code> function displays the first 6 rows of your dataset</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ow)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  Player  Date     Win Map   Mode  Role  Elimination Assists Deaths Damage Heals
  &lt;chr&gt;   &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 player1 8/15/…     1 Sura… Assa… Dama…          28       0      5  11480  2484
2 player1 8/15/…     1 King… Atta… Dama…          17       3      4   6713     0
3 player1 8/15/…     0 New … Robot Tank           27       4      7   5776   122
4 player1 8/15/…     0 Midt… Atta… Dama…           8       3      6   7138     8
5 player1 8/15/…     1 Ilios Atta… Supp…          10       3      4   2163  4849
6 player1 8/15/…     1 Hava… Esco… Tank            7       2      9   4416  2498
# ℹ 1 more variable: Mitigation &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The <code>summary()</code> function provides us with a statistical summary of each column or variable.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ow)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    Player              Date                Win             Map           
 Length:87          Length:87          Min.   :0.0000   Length:87         
 Class :character   Class :character   1st Qu.:0.0000   Class :character  
 Mode  :character   Mode  :character   Median :1.0000   Mode  :character  
                                       Mean   :0.6552                     
                                       3rd Qu.:1.0000                     
                                       Max.   :1.0000                     
     Mode               Role            Elimination       Assists      
 Length:87          Length:87          Min.   : 4.00   Min.   : 0.000  
 Class :character   Class :character   1st Qu.:10.50   1st Qu.: 2.000  
 Mode  :character   Mode  :character   Median :15.00   Median : 6.000  
                                       Mean   :16.68   Mean   : 8.747  
                                       3rd Qu.:21.00   3rd Qu.:12.500  
                                       Max.   :58.00   Max.   :51.000  
     Deaths           Damage          Heals         Mitigation  
 Min.   : 0.000   Min.   :  773   Min.   :    0   Min.   :   0  
 1st Qu.: 4.000   1st Qu.: 2974   1st Qu.:  100   1st Qu.:   0  
 Median : 6.000   Median : 4336   Median : 1322   Median :   0  
 Mean   : 5.989   Mean   : 5166   Mean   : 3214   Mean   :1156  
 3rd Qu.: 8.000   3rd Qu.: 6994   3rd Qu.: 5898   3rd Qu.:1798  
 Max.   :12.000   Max.   :14824   Max.   :18620   Max.   :7253  </code></pre>
</div>
</div>
<p>The <code>str()</code> function gives a structural overview of the data.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ow)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [87 × 12] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Player     : chr [1:87] "player1" "player1" "player1" "player1" ...
 $ Date       : chr [1:87] "8/15/24" "8/15/24" "8/15/24" "8/15/24" ...
 $ Win        : num [1:87] 1 1 0 0 1 1 0 1 1 1 ...
 $ Map        : chr [1:87] "Suravasa" "King's Row" "New Queen Street" "Midtown" ...
 $ Mode       : chr [1:87] "Assault" "Attack Escort" "Robot" "Attack Escort" ...
 $ Role       : chr [1:87] "Damage" "Damage" "Tank" "Damage" ...
 $ Elimination: num [1:87] 28 17 27 8 10 7 22 15 27 8 ...
 $ Assists    : num [1:87] 0 3 4 3 3 2 6 3 8 5 ...
 $ Deaths     : num [1:87] 5 4 7 6 4 9 9 7 4 1 ...
 $ Damage     : num [1:87] 11480 6713 5776 7138 2163 ...
 $ Heals      : num [1:87] 2484 0 122 8 4849 ...
 $ Mitigation : num [1:87] 0 245 2082 828 0 ...
 - attr(*, "spec")=
  .. cols(
  ..   Player = col_character(),
  ..   Date = col_character(),
  ..   Win = col_double(),
  ..   Map = col_character(),
  ..   Mode = col_character(),
  ..   Role = col_character(),
  ..   Elimination = col_double(),
  ..   Assists = col_double(),
  ..   Deaths = col_double(),
  ..   Damage = col_double(),
  ..   Heals = col_double(),
  ..   Mitigation = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>Another useful thing to analyze is looking at all the possible values in your columns - sometimes, the <code>str()</code> function shows all unique values, but other times it gets cut off. We can do it this way:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># output all unique values in the Player column </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(ow<span class="sc">$</span>Player)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "player1" "player2"</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OR use the apply function for the unique function</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(ow, unique)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$Player
[1] "player1" "player2"

$Date
[1] "8/15/24" "8/14/24" "8/13/24" "8/12/24" "8/16/24" "8/10/24" "8/17/24"

$Win
[1] 1 0

$Map
 [1] "Suravasa"              "King's Row"            "New Queen Street"     
 [4] "Midtown"               "Ilios"                 "Havana"               
 [7] "Blizzard World"        "Junkertown"            "New Junk City"        
[10] "Paraiso"               "Runasapi"              "Nepal"                
[13] "Colosseo"              "Shambali Monastery"    "Busan"                
[16] "Rialto"                "Oasis"                 "Eichenwalde"          
[19] "Lijiang Tower"         "Route 66"              "Antarctic Peninsula"  
[22] "Circuit Royal"         "Hollywood"             "Watchpoint: Gibraltar"
[25] "Samoa"                 "Numbani"               "Dorado"               

$Mode
[1] "Assault"       "Attack Escort" "Robot"         "Attack"       
[5] "Escort"       

$Role
[1] "Damage"  "Tank"    "Support"

$Elimination
 [1] 28 17 27  8 10  7 22 15 21 14 16 20  5 11 33 19 34 23  6 18  9 12 29 26  4
[26] 13 58

$Assists
 [1]  0  3  4  2  6  8  5  7 12 10 11 16  1 13 26 20 22 14 30  9 19 17 15 23 51

$Deaths
 [1]  5  4  7  6  9  1  3 10  8 12  2  0 11

$Damage
 [1] 11480  6713  5776  7138  2163  4416  7538 10948  9735  4102  7234  6301
[13]  1166  4403  6042  8466  5083  4307  7841  2509  5076  9435  8793  6227
[25] 13201  4548  7355  6344  2801 10388  4632 13538  8332 14824  2328  7634
[37]  8196  3417  5347  3869  3395  5768  6849  3440  1886  3324  9540  2458
[49]  7477  1755  4336  3506  2364  5320  3444  4283  3849  9577  3349  2520
[61]  1844  2934  5021  1445  4768  2309  3290  2636  3812  2239  3100  2999
[73]  2949  4437   773  2504  3032  3198  1015  1506  5172  4210  3694  1907
[85]  3736  4602 12204

$Heals
 [1]  2484     0   122     8  4849  2498  2260   225   382   941   129   187
[13]    78  5917  1900    16  1542  1490  1342   243  1322  1185   543  2866
[25]   731   734   330    63  7782   727  7352   241   722   536   822  7641
[37]  9179  7375   942    21 12938  7404  4384  6813  6107 11855  4188  9333
[49]  2738  1018  2832  3286  6780  5880  8181  4120 11971  1142  8902  2698
[61]  4689  8910  8853  2510  4060 10032  3860  8015  9545 18620

$Mitigation
 [1]    0  245 2082  828 1068 5654 6078 2012 4439  486 1386 1735 2692 3197 6532
[16] 3251 5070 2760 1994  980 5243 3220 4639 5234 7253 1686  734 1275  928 3676
[31] 1860  364  900  462 2472  220  548 2886 3901  598</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can access a column in a <code>data.frame</code> by using the <code>$</code> operator. When we do this, we can treat the column as if it is a single vector.</p>
</div>
</div>
<p>If we analyze the output of the <code>summary()</code> and the <code>str()</code> function, we can see that the <code>Date</code> column is categorized as a <code>character</code>. Let’s reassign it’s class by using the <code>as.Date</code> function.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' because the values of Date appear as MM/DD/YY in the data, we will use %m/%d/%y to follow the same format.</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co">#' %y represents year using 2 digits, %Y represents using 4 digits</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>ow<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(ow<span class="sc">$</span>Date, <span class="at">format =</span> <span class="st">"%m/%d/%y"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(ow<span class="sc">$</span>Date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Date"</code></pre>
</div>
</div>
</section>
<section id="visualizing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-data">Visualizing the data</h2>
<p>The output of <code>summary()</code> and <code>str()</code> told us that we have several <code>numeric</code> columns in our data: <code>eliminations</code>, <code>assists</code>, <code>deaths</code>, <code>damage</code>, <code>heals</code>, and <code>mitigation</code>.</p>
<p>Let’s first visualize a histogram for the <code>damage</code> column to determine its distribution.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># using base R function: hist()</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ow<span class="sc">$</span>Damage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05_Dataframes_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also create a boxplot as another way to view its distribution and determine what our potential outliers would look like.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># using base R function: boxplot()</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(ow<span class="sc">$</span>Damage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05_Dataframes_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="data-transformation" class="level2">
<h2 class="anchored" data-anchor-id="data-transformation">Data Transformation</h2>
<div class="callout-example-white">
<p><strong>Convert the <code>data.frame</code> from <code>wide</code> to <code>long</code></strong></p>
<p>Transformation Functions:</p>
<ul>
<li><p><code>pivot_longer()</code> -&gt; function to go from <code>wide</code> to <code>long</code></p></li>
<li><p><code>pivot_wider()</code> -&gt; function to go from <code>long</code> to <code>wide</code></p></li>
</ul>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ow_long <span class="ot">&lt;-</span> ow <span class="sc">%&gt;%</span> <span class="fu">pivot_longer</span>(<span class="at">cols=</span><span class="fu">c</span>(<span class="st">"Elimination"</span>, <span class="st">"Assists"</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Deaths"</span>, <span class="st">"Damage"</span>, <span class="st">"Heals"</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Mitigation"</span>), </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">names_to =</span> <span class="st">"value_type"</span>, </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                                <span class="at">values_to =</span> <span class="st">"value"</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ow_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  Player  Date         Win Map      Mode    Role   value_type  value
  &lt;chr&gt;   &lt;date&gt;     &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;       &lt;dbl&gt;
1 player1 2024-08-15     1 Suravasa Assault Damage Elimination    28
2 player1 2024-08-15     1 Suravasa Assault Damage Assists         0
3 player1 2024-08-15     1 Suravasa Assault Damage Deaths          5
4 player1 2024-08-15     1 Suravasa Assault Damage Damage      11480
5 player1 2024-08-15     1 Suravasa Assault Damage Heals        2484
6 player1 2024-08-15     1 Suravasa Assault Damage Mitigation      0</code></pre>
</div>
</div>
</div>
<p>Concepts to know:</p>
<ul>
<li><p><code>%&gt;%</code> -&gt; pipe operator, takes the output of the expression of the LHS and passes it to the first argument on its RHS</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(ow)</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co">#ow %&gt;% summary()</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>ow <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>() <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    Player               Date                 Win             Map           
 Length:6           Min.   :2024-08-15   Min.   :0.0000   Length:6          
 Class :character   1st Qu.:2024-08-15   1st Qu.:0.2500   Class :character  
 Mode  :character   Median :2024-08-15   Median :1.0000   Mode  :character  
                    Mean   :2024-08-15   Mean   :0.6667                     
                    3rd Qu.:2024-08-15   3rd Qu.:1.0000                     
                    Max.   :2024-08-15   Max.   :1.0000                     
     Mode               Role            Elimination       Assists    
 Length:6           Length:6           Min.   : 7.00   Min.   :0.00  
 Class :character   Class :character   1st Qu.: 8.50   1st Qu.:2.25  
 Mode  :character   Mode  :character   Median :13.50   Median :3.00  
                                       Mean   :16.17   Mean   :2.50  
                                       3rd Qu.:24.50   3rd Qu.:3.00  
                                       Max.   :28.00   Max.   :4.00  
     Deaths          Damage          Heals          Mitigation     
 Min.   :4.000   Min.   : 2163   Min.   :   0.0   Min.   :   0.00  
 1st Qu.:4.250   1st Qu.: 4756   1st Qu.:  36.5   1st Qu.:  61.25  
 Median :5.500   Median : 6244   Median :1303.0   Median : 536.50  
 Mean   :5.833   Mean   : 6281   Mean   :1660.2   Mean   : 703.83  
 3rd Qu.:6.750   3rd Qu.: 7032   3rd Qu.:2494.5   3rd Qu.:1008.00  
 Max.   :9.000   Max.   :11480   Max.   :4849.0   Max.   :2082.00  </code></pre>
</div>
</div>
<ul>
<li>The example above states: with the <code>overwatch</code> dataset, use the function <code>head()</code> and from the output of <code>head()</code>, use the function <code>summary().</code></li>
</ul></li>
</ul>
<section id="dplyr" class="level3">
<h3 class="anchored" data-anchor-id="dplyr">Dplyr</h3>
<p><code>dplyr</code> is a package in <code>R</code> that is part of <code>tidyverse</code>, it is the main package for data manipulation that is <em>super</em> intuitive. It is often described as “grammar for data manipulation”</p>
<ul>
<li><code>mutate()</code> - adds new variables that are “manipulations” of other variables that already exist in your data / create or transform columns</li>
</ul>
<div class="callout-example">
<p><strong>Using <code>mutate()</code></strong></p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">8</span>,<span class="dv">10</span>, <span class="cn">NA</span>, <span class="dv">5</span>, <span class="dv">6</span>))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">x2 =</span> x<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   x  x2
1  1   1
2  3   9
3  8  64
4 10 100
5 NA  NA
6  5  25
7  6  36</code></pre>
</div>
</div>
</div>
<ul>
<li><code>filter()</code> - filters or picks cases based on their values</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>filter()</code> function will always return or filter your data for conditions that are TRUE <strong>meaning conditions that are FALSE or conditions that are NA will not be returned</strong>.</p>
<ul>
<li><p>If you want to retain the missing values, you have to explicitly filter for it as well.</p></li>
<li><p>Use <code>is.na()</code> to determine if value is missing.</p></li>
</ul>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">8</span>,<span class="dv">10</span>, <span class="cn">NA</span>, <span class="dv">5</span>, <span class="dv">6</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># NA is dropped as well</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>filter <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(x <span class="sc">!=</span> <span class="dv">3</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>filter</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   x
1  1
2  8
3 10
4  5
5  6</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>filter <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(x <span class="sc">!=</span> <span class="dv">3</span> <span class="sc">|</span> <span class="fu">is.na</span>(x))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>filter</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   x
1  1
2  8
3 10
4 NA
5  5
6  6</code></pre>
</div>
</div>
</div>
</div>
<ul>
<li><p><code>select()</code> - picks based on columns/variables</p></li>
<li><p><code>arrange()</code> - reorder rows</p></li>
<li><p><code>summarise()</code> - collapse into specified summary statistics</p></li>
<li><p><code>group_by()</code> - allows functions to be conducted by group</p></li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<code>ungroup()</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>When you use <code>group_by()</code>, you should try your best to <code>ungroup()</code> your data afterwards so that any following operation is not done within groups again.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">student =</span> <span class="fu">c</span>(<span class="st">"X"</span>, <span class="st">"X"</span>, <span class="st">"X"</span>, <span class="st">"Y"</span>, <span class="st">"Y"</span>, <span class="st">"Y"</span>), </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">score =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">98</span>, <span class="dv">85</span>, <span class="dv">90</span>, <span class="dv">96</span>, <span class="dv">98</span>), </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">class =</span> <span class="fu">c</span>(<span class="st">"Math"</span>, <span class="st">"Math"</span>, <span class="st">"Bio"</span>, <span class="st">"Bio"</span>, <span class="st">"Bio"</span>, <span class="st">"Math"</span>))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>mean_student <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">group_by</span>(class, student) <span class="sc">%&gt;%</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">summarise</span>(<span class="at">average_score =</span> <span class="fu">mean</span>(score))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'class'. You can override using the
`.groups` argument.</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mean_student)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   class [2]
  class student average_score
  &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;
1 Bio   X                  85
2 Bio   Y                  93
3 Math  X                  99
4 Math  Y                  98</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mean_student <span class="ot">&lt;-</span> mean_student <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sum_score =</span> <span class="fu">sum</span>(average_score))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mean_student)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  class sum_score
  &lt;chr&gt;     &lt;dbl&gt;
1 Bio         178
2 Math        197</code></pre>
</div>
</div>
<p><code>summarise()</code> drops one level of grouping but the highest level is retained, as shown in the second operation. Running the same lines of code but including <code>ungroup()</code> will provide an <code>overall_sum</code> at the end, instead of a <code>sum</code> by <code>class</code>.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>mean_student <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">group_by</span>(class, student) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">summarise</span>(<span class="at">average_score =</span> <span class="fu">mean</span>(score)) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'class'. You can override using the
`.groups` argument.</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mean_student)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  class student average_score
  &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;
1 Bio   X                  85
2 Bio   Y                  93
3 Math  X                  99
4 Math  Y                  98</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>mean_student <span class="ot">&lt;-</span> mean_student <span class="sc">%&gt;%</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sum_score =</span> <span class="fu">sum</span>(average_score))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mean_student)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  sum_score
      &lt;dbl&gt;
1       375</code></pre>
</div>
</div>
</div>
</div>
<div class="callout-example-white">
<p><strong>What is the total number of wins and losses and percentage of wins/losses for each Player? By each Date? Create a visualization.</strong></p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a new data.frame that is a copy of ow_long, group it by Player &amp; Date, and use the summarise function to calculate the total number of wins/loses and its percent</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>player_wins <span class="ot">&lt;-</span> ow_long <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Player, Date) <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">wins =</span> <span class="fu">sum</span>(Win),</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">pct_win =</span> <span class="fu">sum</span>(Win)<span class="sc">/</span><span class="fu">n</span>() <span class="sc">*</span> <span class="dv">100</span>, </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">lose =</span> <span class="fu">n</span>() <span class="sc">-</span> <span class="fu">sum</span>(Win), </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">pct_lose =</span> lose<span class="sc">/</span><span class="fu">n</span>() <span class="sc">*</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Player'. You can override using the
`.groups` argument.</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(player_wins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
# Groups:   Player [2]
   Player  Date        wins pct_win  lose pct_lose
   &lt;chr&gt;   &lt;date&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
 1 player1 2024-08-12    24    50      24     50  
 2 player1 2024-08-13    78    68.4    36     31.6
 3 player1 2024-08-14    66    73.3    24     26.7
 4 player1 2024-08-15    48    66.7    24     33.3
 5 player1 2024-08-16     6    50       6     50  
 6 player2 2024-08-10     6    50       6     50  
 7 player2 2024-08-13    60    83.3    12     16.7
 8 player2 2024-08-14     6   100       0      0  
 9 player2 2024-08-15    36    75      12     25  
10 player2 2024-08-17    12    25      36     75  </code></pre>
</div>
</div>
<p>Create a bar-graph:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting number of wins</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>bar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> player_wins, <span class="fu">aes</span>(<span class="at">x=</span> Date, <span class="at">y=</span> wins)) <span class="sc">+</span> </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Player), <span class="at">position=</span><span class="st">"dodge"</span>, <span class="at">stat=</span><span class="st">"identity"</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05_Dataframes_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Create a line-graph:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>line <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> player_wins, <span class="fu">aes</span>(<span class="at">x=</span> Date, <span class="at">y=</span> wins)) <span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color =</span> Player)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(line)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05_Dataframes_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="callout-example-white">
<p><strong>What is the total number of eliminations and damage by Role? Create a visualization.</strong></p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>role_stats <span class="ot">&lt;-</span> ow_long <span class="sc">%&gt;%</span> </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Player, Role, value_type) <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sum_val =</span> <span class="fu">sum</span>(value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Player', 'Role'. You can override using
the `.groups` argument.</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(role_stats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
# Groups:   Player, Role [1]
  Player  Role   value_type  sum_val
  &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;         &lt;dbl&gt;
1 player1 Damage Assists          61
2 player1 Damage Damage       139972
3 player1 Damage Deaths          130
4 player1 Damage Elimination     415
5 player1 Damage Heals         14135
6 player1 Damage Mitigation    12348</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(role_stats <span class="sc">%&gt;%</span> <span class="fu">filter</span>(value_type <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Elimination"</span>, <span class="st">"Damage"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
# Groups:   Player, Role [6]
   Player  Role    value_type  sum_val
   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt;
 1 player1 Damage  Damage       139972
 2 player1 Damage  Elimination     415
 3 player1 Support Damage        35623
 4 player1 Support Elimination     122
 5 player1 Tank    Damage       163196
 6 player1 Tank    Elimination     401
 7 player2 Damage  Damage         2934
 8 player2 Damage  Elimination       7
 9 player2 Support Damage        87308
10 player2 Support Elimination     435
11 player2 Tank    Damage        20389
12 player2 Tank    Elimination      71</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>chart <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> role_stats, <span class="fu">aes</span>(<span class="at">x =</span> Role, <span class="at">y =</span> sum_val)) <span class="sc">+</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>, <span class="fu">aes</span>(<span class="at">fill =</span> Player)) <span class="sc">+</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> value_type, <span class="at">scales =</span> <span class="st">"free_y"</span>)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(chart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05_Dataframes_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also re-order the way our items appear in our chart by making our ordering variables factors and setting its levels. Below, we set <code>Role</code> and <code>value_type</code> to be a factor where the levels are in the order we want these categories to appear on our chart (the x-axis for <code>Role</code> and the various facets for <code>value_type</code>).</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># re-order the x-axis by changing Role into a factor with wanted order of levels</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Tank, Support, Damage </span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>role_stats<span class="sc">$</span>Role <span class="ot">&lt;-</span> <span class="fu">factor</span>(role_stats<span class="sc">$</span>Role, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Tank"</span>, <span class="st">"Support"</span>, <span class="st">"Damage"</span>))</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(role_stats<span class="sc">$</span>Role)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Damage  Support Tank   
Levels: Tank Support Damage</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>role_stats<span class="sc">$</span>value_type <span class="ot">&lt;-</span> <span class="fu">factor</span>(role_stats<span class="sc">$</span>value_type, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Elimination"</span>, </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>                                                                  <span class="st">"Assists"</span>, </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>                                                                  <span class="st">"Deaths"</span>, </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>                                                                  <span class="st">"Damage"</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>                                                                  <span class="st">"Heals"</span>,</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>                                                                  <span class="st">"Mitigation"</span>))</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(role_stats<span class="sc">$</span>value_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Assists     Damage      Deaths      Elimination Heals       Mitigation 
Levels: Elimination Assists Deaths Damage Heals Mitigation</code></pre>
</div>
</div>
<p>Re-define the plot:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>chart <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> role_stats, <span class="fu">aes</span>(<span class="at">x =</span> Role, <span class="at">y =</span> sum_val)) <span class="sc">+</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>, <span class="fu">aes</span>(<span class="at">fill =</span> Player)) <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> value_type, <span class="at">scales =</span> <span class="st">"free_y"</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(chart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05_Dataframes_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="merging" class="level2">
<h2 class="anchored" data-anchor-id="merging">Merging</h2>
<div class="callout-recall">
<p><strong>Recall</strong>: Merging data sets is the process of combining two or more data sets based on common columns or row indices. This is common in data analytics when you need to bring information together from different sources into one single data set.</p>
</div>
<section id="join-functions" class="level3">
<h3 class="anchored" data-anchor-id="join-functions">Join Functions</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Join Types
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Join Function</th>
<th>Description</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>inner_join()</code></td>
<td>Keeps only rows that have a match in <strong>both</strong> datasets.</td>
<td>Overlap only</td>
</tr>
<tr class="even">
<td><code>left_join()</code></td>
<td>Keeps <strong>all rows from the left</strong> dataset, filling with <code>NA</code> if no match on right.</td>
<td>Keep the left side</td>
</tr>
<tr class="odd">
<td><code>right_join()</code></td>
<td>Keeps <strong>all rows from the right</strong> dataset, filling with <code>NA</code> if no match on left.</td>
<td>Keep the right side</td>
</tr>
<tr class="even">
<td><code>full_join()</code></td>
<td>Keeps <strong>all rows from both</strong> datasets; matches are combined, non-matches get <code>NA</code>.</td>
<td>Keep everything</td>
</tr>
<tr class="odd">
<td><code>semi_join()</code></td>
<td>Filters the left dataset to only rows that have a match in the right; doesn’t add columns.</td>
<td>Left rows with matches</td>
</tr>
<tr class="even">
<td><code>anti_join()</code></td>
<td>Filters the left dataset to rows that <strong>do not</strong> have a match in the right.</td>
<td>Left rows without matches</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>To further analyze our data, we will merge the <code>overwatch_heros.csv</code> into our current <code>data.frame.</code>In addition to the Overwatch dataset, the accompanying dataset (<code>overwatch_heros</code>) lists the heroes played in each game. We know that each row in the original Overwatch dataset we’ve been working with corresponds to a single game. Because of the game’s mechanics, players are allowed to switch heroes during a match. As a result, in the heroes dataset, you’ll see that a player may have played multiple heroes within the same game.</p>
<ul>
<li><p>The <code>overwatch_heros</code> data set contains these attributes:</p>
<ul>
<li>Player</li>
<li>Date</li>
<li>Win</li>
<li>Map</li>
<li>Mode</li>
<li>Role</li>
<li>Percent Played</li>
<li>Hero</li>
</ul></li>
</ul>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in the new data set</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>dir <span class="ot">&lt;-</span> <span class="st">"/Users/rdominguez/Documents/MA500/Lessons/datasets/"</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>hero <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">paste0</span>(dir, <span class="st">"overwatch_heros.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 99 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (6): Player, Date, Map, Mode, Role, Hero
dbl (2): Win, Percent Played

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(hero)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [99 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Player        : chr [1:99] "player1" "player1" "player1" "player1" ...
 $ Date          : chr [1:99] "8/15/24" "8/15/24" "8/15/24" "8/15/24" ...
 $ Win           : num [1:99] 1 1 1 0 0 1 1 0 0 1 ...
 $ Map           : chr [1:99] "Suravasa" "Suravasa" "King's Row" "New Queen Street" ...
 $ Mode          : chr [1:99] "Assault" "Assault" "Attack Escort" "Robot" ...
 $ Role          : chr [1:99] "Damage" "Damage" "Damage" "Tank" ...
 $ Percent Played: num [1:99] 82 18 100 100 100 100 100 48 52 100 ...
 $ Hero          : chr [1:99] "Sombra" "Bastion" "Sombra" "Dva" ...
 - attr(*, "spec")=
  .. cols(
  ..   Player = col_character(),
  ..   Date = col_character(),
  ..   Win = col_double(),
  ..   Map = col_character(),
  ..   Mode = col_character(),
  ..   Role = col_character(),
  ..   `Percent Played` = col_double(),
  ..   Hero = col_character()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set the Date column as a Date data type</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>hero<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(hero<span class="sc">$</span>Date, <span class="at">format =</span> <span class="st">"%m/%d/%y"</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(hero<span class="sc">$</span>Date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Date"</code></pre>
</div>
</div>
<p>The output of <code>str()</code> shows that the hero data frame contains more observations than the Overwatch dataset, which has 87 entries.</p>
<p>When you use the <code>left_join</code> function to merge the <code>ow</code> data frame with the <code>hero</code> data frame, it will match all key values from the <code>hero</code> data to the <code>ow</code> data. However, the first time you run this, you’ll encounter a “many-to-many relationship” warning. This means that the join will occur, but it will generate all possible combinations of our key columns—Player, Date, Win, Map, Mode, and Role—with the various corresponding heroes.</p>
<p>To simplify things, we’ll only join the rows associated with the heroes that were played the most during each game.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>hero_most_played <span class="ot">&lt;-</span> hero <span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Player, Date, Win, Map, Mode, Role) <span class="sc">%&gt;%</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Percent Played</span><span class="st">`</span> <span class="sc">==</span> <span class="fu">max</span>(<span class="st">`</span><span class="at">Percent Played</span><span class="st">`</span>))</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>ow_with_hero <span class="ot">&lt;-</span> <span class="fu">left_join</span>(ow, hero_most_played, <span class="at">by=</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">c</span>(<span class="st">"Player"</span>, <span class="st">"Date"</span>, <span class="st">"Win"</span>,</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Map"</span>, <span class="st">"Mode"</span>, <span class="st">"Role"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in left_join(ow, hero_most_played, by = c("Player", "Date", "Win", : Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 24 of `x` matches multiple rows in `y`.
ℹ Row 24 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
</div>
<p>When merging, you may encounter a <strong>“many-to-many relationship” warning</strong>. This occurs because there are duplicate combinations of our key indicators: Player, Date, Win, Map, Mode, Role. In other words, the dataset contains <strong>multiple games played by the same player, on the same date, with the same result, on the same map, mode, and role</strong>. Normally, this issue would be prevented by assigning a <strong>unique game identifier</strong>. However, this dataset does not include such an identifier. As a result, a player can appear in several games on the same day—even under the exact same conditions (map, role, and mode).</p>
<p>To move forward with analysis, we will <strong>detect and remove these duplicate entries</strong> to ensure clean merges.</p>
<ul>
<li>tldr: issue 1 with the merge: The dataset lacks a unique game identifier, which causes duplicate entries.</li>
</ul>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># this code counts all possible combinations of our key indicators and filters to the set that shows up more than once</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>duplicate <span class="ot">&lt;-</span> ow <span class="sc">%&gt;%</span> </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Player, Date, Win, Map, Mode, Role) <span class="sc">%&gt;%</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  Player  Date         Win Map      Mode    Role       n
  &lt;chr&gt;   &lt;date&gt;     &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;int&gt;
1 player1 2024-08-13     1 Suravasa Assault Damage     2</code></pre>
</div>
</div>
<p>After we find this duplicate combination of our key indicators, we will remove it from our <code>ow_with_hero</code> data.frame and move on with our analysis. This will be done using <code>anti_join</code>.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>ow_with_hero <span class="ot">&lt;-</span> ow_with_hero <span class="sc">%&gt;%</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">anti_join</span>(duplicate, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Player"</span>, <span class="st">"Date"</span>, <span class="st">"Win"</span>, <span class="st">"Map"</span>,</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Mode"</span>, <span class="st">"Role"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="callout-example-white">
<p><strong>Analyze player 2’s statistics by their Heroes played.</strong></p>
<p>First, let’s transform our newly merged data from <code>wide</code> to <code>long</code> for easier analysis.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>ow_long_with_hero <span class="ot">&lt;-</span> ow_with_hero <span class="sc">%&gt;%</span> <span class="fu">pivot_longer</span>(<span class="at">cols=</span><span class="fu">c</span>(<span class="st">"Elimination"</span>, <span class="st">"Assists"</span>,</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Deaths"</span>, <span class="st">"Damage"</span>, <span class="st">"Heals"</span>,</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Mitigation"</span>), </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">names_to =</span> <span class="st">"value_type"</span>, </span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>                                <span class="at">values_to =</span> <span class="st">"value"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Next, we are going to create a new dataset that only contains <code>Player 2</code>’s records and summarize from there.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>player2 <span class="ot">&lt;-</span> ow_long_with_hero <span class="sc">%&gt;%</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Player <span class="sc">==</span> <span class="st">"player2"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Player, Hero, value_type) <span class="sc">%&gt;%</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sum_val =</span> <span class="fu">sum</span>(value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Player', 'Hero'. You can override using
the `.groups` argument.</code></pre>
</div>
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(player2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 4
# Groups:   Player, Hero [5]
   Player  Hero       value_type  sum_val
   &lt;chr&gt;   &lt;chr&gt;      &lt;chr&gt;         &lt;dbl&gt;
 1 player2 Lifeweaver Assists          17
 2 player2 Lifeweaver Damage         2239
 3 player2 Lifeweaver Deaths            3
 4 player2 Lifeweaver Elimination      11
 5 player2 Lifeweaver Heals          8181
 6 player2 Lifeweaver Mitigation        0
 7 player2 Mauga      Assists          17
 8 player2 Mauga      Damage        10449
 9 player2 Mauga      Deaths           16
10 player2 Mauga      Elimination      44
# ℹ 20 more rows</code></pre>
</div>
</div>
<p>Let’s just create another bar-chart to visualize these results!</p>
<div class="cell">
<details open="" class="code-fold">
<summary>hide code</summary>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>p2_facet <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> player2, <span class="fu">aes</span>(<span class="at">x=</span>Hero, <span class="at">y=</span>sum_val))<span class="sc">+</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>)<span class="sc">+</span><span class="fu">facet_wrap</span>(<span class="sc">~</span>value_type, <span class="at">scales=</span><span class="st">"free_y"</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p2_facet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05_Dataframes_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04_CLF.html" class="pagination-link" aria-label="Conditionals, Loops, and Functions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Conditionals, Loops, and Functions</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06_Visualizations.html" class="pagination-link" aria-label="Data Visualizations">
        <span class="nav-page-text">Data Visualizations</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>